"""adding audit

Revision ID: d5a77ab20d69
Revises: b8d52189d4b3
Create Date: 2020-04-12 11:46:43.008694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a77ab20d69'
down_revision = 'b8d52189d4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
